import { Executor } from '@stratix/core';

@Executor({
  name: 'sampleWorker',
  description: 'Sample worker executor generated by Stratix CLI'
})
export default class SampleExecutor {
  async execute(payload: Record<string, unknown> = {}): Promise<{
    success: boolean;
    data: Record<string, unknown>;
  }> {
    return {
      success: true,
      data: payload
    };
  }
}
