/**
 * @stratix/database 数据库类型定义
 */

import { Knex } from 'knex';

/**
 * 数据库配置接口，继承自Knex.Config
 */
export interface DatabaseConfig extends Knex.Config {
  /**
   * 是否启用调试模式
   */
  debug?: boolean;

  /**
   * 多数据库连接配置
   */
  connections?: Record<string, Knex.Config>;

  /**
   * 模型配置
   */
  models?: {
    /**
     * 模型文件目录
     */
    directory?: string;

    /**
     * 基础模型类名
     */
    baseClass?: string;

    /**
     * 是否自动注册目录下所有模型
     */
    autoRegister?: boolean;
  };

  /**
   * 迁移配置
   */
  migrations?: Knex.MigratorConfig & {
    /**
     * 是否自动从模型生成迁移
     */
    autoGenerate?: boolean;

    /**
     * 自动迁移生成目录
     */
    autoGenerateDirectory?: string;

    /**
     * 迁移模板文件
     */
    templateFile?: string;

    /**
     * 表名前缀
     */
    tablePrefix?: string;
  };

  /**
   * 种子配置
   */
  seeds?: {
    /**
     * 种子文件目录
     */
    directory?: string;

    /**
     * 不同环境使用的种子目录
     */
    environment?: Record<string, string[]>;
  };

  /**
   * 缓存配置
   */
  cache?: {
    /**
     * 是否启用缓存
     */
    enabled?: boolean;

    /**
     * 缓存前缀
     */
    prefix?: string;

    /**
     * 默认缓存时间（毫秒）
     */
    ttl?: number;

    /**
     * 查询缓存配置
     */
    queries?: {
      /**
       * 是否启用查询缓存
       */
      enabled?: boolean;

      /**
       * 查询缓存时间（毫秒）
       */
      ttl?: number;
    };

    /**
     * 模型缓存配置
     */
    models?: {
      /**
       * 是否启用模型缓存
       */
      enabled?: boolean;

      /**
       * 模型缓存时间（毫秒）
       */
      ttl?: number;
    };
  };

  /**
   * 连接成功后的回调函数
   */
  onConnect?: (context: any) => Promise<void> | void;
}

/**
 * 数据库驱动枚举
 */
export enum DatabaseDriver {
  PostgreSQL = 'postgresql',
  MySQL = 'mysql',
  SQLite = 'sqlite3',
  Oracle = 'oracledb',
  MSSQL = 'mssql'
}

/**
 * 数据库连接状态
 */
export enum ConnectionStatus {
  Disconnected = 'disconnected',
  Connected = 'connected',
  Error = 'error'
}

/**
 * ID字段类型
 */
export type IdFieldType = 'cuid' | 'uuid' | 'autoincrement';

/**
 * 模型钩子回调函数类型
 */
export type ModelHookCallback = (
  data: any,
  context?: any
) => Promise<any> | any;

/**
 * 查询选项
 */
export interface QueryOptions {
  /**
   * 事务对象
   */
  transaction?: Knex.Transaction;

  /**
   * 是否使用缓存
   */
  useCache?: boolean;

  /**
   * 缓存时间（毫秒）
   */
  cacheTTL?: number;

  /**
   * 查询上下文
   */
  context?: any;

  /**
   * 数据库连接名称
   */
  connection?: string;

  /**
   * 是否包含已软删除的记录
   */
  withTrashed?: boolean;

  /**
   * 仅获取已软删除的记录
   */
  onlyTrashed?: boolean;

  /**
   * 要应用的作用域
   */
  scopes?: Array<string | Function>;
}

/**
 * 分页结果
 */
export interface PaginationResult<T> {
  /**
   * 数据
   */
  data: T[];

  /**
   * 总记录数
   */
  total: number;

  /**
   * 当前页
   */
  currentPage: number;

  /**
   * 每页记录数
   */
  perPage: number;

  /**
   * 总页数
   */
  lastPage: number;

  /**
   * 是否有下一页
   */
  hasNextPage: boolean;

  /**
   * 是否有上一页
   */
  hasPreviousPage: boolean;
}

/**
 * 列信息接口
 */
export interface ColumnInfo {
  /**
   * 列名
   */
  name: string;

  /**
   * 数据类型
   */
  type: string;

  /**
   * 是否可为空
   */
  nullable: boolean;

  /**
   * 默认值
   */
  defaultValue: any;

  /**
   * 列注释
   */
  comment?: string;

  /**
   * 字符长度(如适用)
   */
  maxLength?: number;
}

/**
 * 索引信息接口
 */
export interface IndexInfo {
  /**
   * 索引名称
   */
  name: string;

  /**
   * 包含的列
   */
  columns: string[];

  /**
   * 是否唯一索引
   */
  unique: boolean;

  /**
   * 是否主键
   */
  primary: boolean;
}

/**
 * 表信息接口
 */
export interface TableInfo {
  /**
   * 表名
   */
  name: string;

  /**
   * 表注释
   */
  comment?: string;

  /**
   * 列信息
   */
  columns: ColumnInfo[];

  /**
   * 索引信息
   */
  indexes?: IndexInfo[];
}
