packages:
  - 'packages/*'
  - 'packages/devtools/client'
overrides:
  ioredis: 5.11.1
  vitest@4.1.10>vite: 8.0.16
allowBuilds:
  better-sqlite3: true
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  ssh2: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - fs-extra@11.4.0
