/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as ClerkRouteRouteImport } from './routes/clerk/route';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers';
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks';
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students';
import { Route as AuthenticatedDataQueryRouteImport } from './routes/_authenticated/data-query';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses';
import { Route as AuthenticatedBasicManagementRouteImport } from './routes/_authenticated/basic-management';
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance';
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics';
import { Route as errors503RouteImport } from './routes/(errors)/503';
import { Route as errors500RouteImport } from './routes/(errors)/500';
import { Route as errors404RouteImport } from './routes/(errors)/404';
import { Route as errors403RouteImport } from './routes/(errors)/403';
import { Route as errors401RouteImport } from './routes/(errors)/401';
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up';
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2';
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in';
import { Route as authOtpRouteImport } from './routes/(auth)/otp';
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password';
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route';
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route';
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route';
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index';
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index';
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index';
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index';
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index';
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index';
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management';
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up';
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in';
import { Route as AuthenticatedTasksSyncRouteImport } from './routes/_authenticated/tasks/sync';
import { Route as AuthenticatedTasksSettingsRouteImport } from './routes/_authenticated/tasks/settings';
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications';
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display';
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance';
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account';
import { Route as AuthenticatedCoursesSettingsRouteImport } from './routes/_authenticated/courses/settings';
import { Route as AuthenticatedCoursesScheduleRouteImport } from './routes/_authenticated/courses/schedule';
const ClerkRouteRoute = ClerkRouteRouteImport.update({
    id: '/clerk',
    path: '/clerk',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedDataQueryRoute = AuthenticatedDataQueryRouteImport.update({
    id: '/data-query',
    path: '/data-query',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedBasicManagementRoute = AuthenticatedBasicManagementRouteImport.update({
    id: '/basic-management',
    path: '/basic-management',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const errors503Route = errors503RouteImport.update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRouteImport,
});
const errors500Route = errors500RouteImport.update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRouteImport,
});
const errors404Route = errors404RouteImport.update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
});
const errors403Route = errors403RouteImport.update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRouteImport,
});
const errors401Route = errors401RouteImport.update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRouteImport,
});
const authSignUpRoute = authSignUpRouteImport.update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
});
const authSignIn2Route = authSignIn2RouteImport.update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRouteImport,
});
const authSignInRoute = authSignInRouteImport.update({
    id: '/(auth)/sign-in',
    path: '/sign-in',
    getParentRoute: () => rootRouteImport,
});
const authOtpRoute = authOtpRouteImport.update({
    id: '/(auth)/otp',
    path: '/otp',
    getParentRoute: () => rootRouteImport,
});
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
});
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => ClerkRouteRoute,
});
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
    id: '/(auth)',
    getParentRoute: () => ClerkRouteRoute,
});
const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTasksRoute,
});
const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
});
const AuthenticatedHelpCenterIndexRoute = AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const ClerkAuthenticatedUserManagementRoute = ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
});
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => ClerkauthRouteRoute,
});
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => ClerkauthRouteRoute,
});
const AuthenticatedTasksSyncRoute = AuthenticatedTasksSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedTasksRoute,
});
const AuthenticatedTasksSettingsRoute = AuthenticatedTasksSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTasksRoute,
});
const AuthenticatedSettingsNotificationsRoute = AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
});
const AuthenticatedSettingsDisplayRoute = AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
});
const AuthenticatedSettingsAppearanceRoute = AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
});
const AuthenticatedSettingsAccountRoute = AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
});
const AuthenticatedCoursesSettingsRoute = AuthenticatedCoursesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCoursesRoute,
});
const AuthenticatedCoursesScheduleRoute = AuthenticatedCoursesScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedCoursesRoute,
});
const AuthenticatedSettingsRouteRouteChildren = {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute: AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
};
const AuthenticatedSettingsRouteRouteWithChildren = AuthenticatedSettingsRouteRoute._addFileChildren(AuthenticatedSettingsRouteRouteChildren);
const AuthenticatedCoursesRouteChildren = {
    AuthenticatedCoursesScheduleRoute: AuthenticatedCoursesScheduleRoute,
    AuthenticatedCoursesSettingsRoute: AuthenticatedCoursesSettingsRoute,
};
const AuthenticatedCoursesRouteWithChildren = AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren);
const AuthenticatedTasksRouteChildren = {
    AuthenticatedTasksSettingsRoute: AuthenticatedTasksSettingsRoute,
    AuthenticatedTasksSyncRoute: AuthenticatedTasksSyncRoute,
    AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
};
const AuthenticatedTasksRouteWithChildren = AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren);
const AuthenticatedRouteRouteChildren = {
    AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
    AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
    AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
    AuthenticatedBasicManagementRoute: AuthenticatedBasicManagementRoute,
    AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
    AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
    AuthenticatedDataQueryRoute: AuthenticatedDataQueryRoute,
    AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
    AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
    AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
    AuthenticatedIndexRoute: AuthenticatedIndexRoute,
    AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
    AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
    AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
    AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
};
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);
const ClerkauthRouteRouteChildren = {
    ClerkauthSignInRoute: ClerkauthSignInRoute,
    ClerkauthSignUpRoute: ClerkauthSignUpRoute,
};
const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(ClerkauthRouteRouteChildren);
const ClerkAuthenticatedRouteRouteChildren = {
    ClerkAuthenticatedUserManagementRoute: ClerkAuthenticatedUserManagementRoute,
};
const ClerkAuthenticatedRouteRouteWithChildren = ClerkAuthenticatedRouteRoute._addFileChildren(ClerkAuthenticatedRouteRouteChildren);
const ClerkRouteRouteChildren = {
    ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
    ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
};
const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(ClerkRouteRouteChildren);
const rootRouteChildren = {
    AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
    ClerkRouteRoute: ClerkRouteRouteWithChildren,
    authForgotPasswordRoute: authForgotPasswordRoute,
    authOtpRoute: authOtpRoute,
    authSignInRoute: authSignInRoute,
    authSignIn2Route: authSignIn2Route,
    authSignUpRoute: authSignUpRoute,
    errors401Route: errors401Route,
    errors403Route: errors403Route,
    errors404Route: errors404Route,
    errors500Route: errors500Route,
    errors503Route: errors503Route,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
//# sourceMappingURL=routeTree.gen.js.map