/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWpsDriveRouteImport } from './routes/_authenticated/wps-drive'
import { Route as AuthenticatedUserDebugRouteImport } from './routes/_authenticated/user-debug'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedPermissionDebugRouteImport } from './routes/_authenticated/permission-debug'
import { Route as AuthenticatedDataQueryRouteImport } from './routes/_authenticated/data-query'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCourseRescheduleRouteImport } from './routes/_authenticated/course-reschedule'
import { Route as AuthenticatedBasicManagementRouteImport } from './routes/_authenticated/basic-management'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authCallbackRouteImport } from './routes/(auth)/callback'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedWorkflowsRouteRouteImport } from './routes/_authenticated/workflows/route'
import { Route as AuthenticatedSystemConfigRouteRouteImport } from './routes/_authenticated/system-config/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSystemConfigIndexRouteImport } from './routes/_authenticated/system-config/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDataQueryIndexRouteImport } from './routes/_authenticated/data-query/index'
import { Route as AuthenticatedCourseCalendarIndexRouteImport } from './routes/_authenticated/course-calendar/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedWorkflowsVisualizationDemoRouteImport } from './routes/_authenticated/workflows/visualization-demo'
import { Route as AuthenticatedWorkflowsTestRouteImport } from './routes/_authenticated/workflows/test'
import { Route as AuthenticatedWorkflowsSchedulesRouteImport } from './routes/_authenticated/workflows/schedules'
import { Route as AuthenticatedWorkflowsQuickTestRouteImport } from './routes/_authenticated/workflows/quick-test'
import { Route as AuthenticatedWorkflowsLogsRouteImport } from './routes/_authenticated/workflows/logs'
import { Route as AuthenticatedWorkflowsDefinitionsRouteImport } from './routes/_authenticated/workflows/definitions'
import { Route as AuthenticatedWorkflowsCourseRestoreRouteImport } from './routes/_authenticated/workflows/course-restore'
import { Route as AuthenticatedTasksSyncRouteImport } from './routes/_authenticated/tasks/sync'
import { Route as AuthenticatedTasksSettingsRouteImport } from './routes/_authenticated/tasks/settings'
import { Route as AuthenticatedSystemConfigTermRouteImport } from './routes/_authenticated/system-config/term'
import { Route as AuthenticatedSystemConfigSyncRouteImport } from './routes/_authenticated/system-config/sync'
import { Route as AuthenticatedSystemConfigCourseRouteImport } from './routes/_authenticated/system-config/course'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedRbacUsersRouteImport } from './routes/_authenticated/rbac.users'
import { Route as AuthenticatedRbacRolesRouteImport } from './routes/_authenticated/rbac.roles'
import { Route as AuthenticatedRbacPermissionsRouteImport } from './routes/_authenticated/rbac.permissions'
import { Route as AuthenticatedRbacMenusRouteImport } from './routes/_authenticated/rbac.menus'
import { Route as AuthenticatedDataQueryTeachingClassRouteImport } from './routes/_authenticated/data-query/teaching-class'
import { Route as AuthenticatedDataQueryCourseStatsTreeRouteImport } from './routes/_authenticated/data-query/course-stats-tree'
import { Route as AuthenticatedDataQueryCourseStatsRouteImport } from './routes/_authenticated/data-query/course-stats'
import { Route as AuthenticatedDataQueryAbsentHistoryRouteImport } from './routes/_authenticated/data-query/absent-history'
import { Route as AuthenticatedCoursesSettingsRouteImport } from './routes/_authenticated/courses/settings'
import { Route as AuthenticatedCoursesScheduleRouteImport } from './routes/_authenticated/courses/schedule'
import { Route as AuthenticatedCourseCalendarStudentRouteImport } from './routes/_authenticated/course-calendar/student'
import { Route as AuthenticatedAttendanceStudentsRouteImport } from './routes/_authenticated/attendance/students'
import { Route as AuthenticatedAttendanceStudentStatsRouteImport } from './routes/_authenticated/attendance/student-stats'
import { Route as AuthenticatedAttendanceRankingsRouteImport } from './routes/_authenticated/attendance/rankings'
import { Route as AuthenticatedAttendanceOverviewRouteImport } from './routes/_authenticated/attendance/overview'
import { Route as AuthenticatedAttendanceFailedLogsRouteImport } from './routes/_authenticated/attendance/failed-logs'
import { Route as AuthenticatedAttendanceCoursesRouteImport } from './routes/_authenticated/attendance/courses'
import { Route as AuthenticatedAttendanceCourseStatisticsRouteImport } from './routes/_authenticated/attendance/course-statistics'
import { Route as AuthenticatedAttendanceAnalyticsRouteImport } from './routes/_authenticated/attendance/analytics'
import { Route as AuthenticatedWorkflowsInstancesIndexRouteImport } from './routes/_authenticated/workflows/instances/index'
import { Route as AuthenticatedWorkflowsDefinitionsIndexRouteImport } from './routes/_authenticated/workflows/definitions/index'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdRouteImport } from './routes/_authenticated/workflows/instances/$instanceId'
import { Route as AuthenticatedWorkflowsDefinitionsDefinitionIdRouteImport } from './routes/_authenticated/workflows/definitions/$definitionId'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWpsDriveRoute = AuthenticatedWpsDriveRouteImport.update({
  id: '/wps-drive',
  path: '/wps-drive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserDebugRoute = AuthenticatedUserDebugRouteImport.update({
  id: '/user-debug',
  path: '/user-debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionDebugRoute =
  AuthenticatedPermissionDebugRouteImport.update({
    id: '/permission-debug',
    path: '/permission-debug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataQueryRoute = AuthenticatedDataQueryRouteImport.update({
  id: '/data-query',
  path: '/data-query',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourseRescheduleRoute =
  AuthenticatedCourseRescheduleRouteImport.update({
    id: '/course-reschedule',
    path: '/course-reschedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBasicManagementRoute =
  AuthenticatedBasicManagementRouteImport.update({
    id: '/basic-management',
    path: '/basic-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authCallbackRoute = authCallbackRouteImport.update({
  id: '/(auth)/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedWorkflowsRouteRoute =
  AuthenticatedWorkflowsRouteRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemConfigRouteRoute =
  AuthenticatedSystemConfigRouteRouteImport.update({
    id: '/system-config',
    path: '/system-config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedSystemConfigIndexRoute =
  AuthenticatedSystemConfigIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSystemConfigRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataQueryIndexRoute =
  AuthenticatedDataQueryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDataQueryRoute,
  } as any)
const AuthenticatedCourseCalendarIndexRoute =
  AuthenticatedCourseCalendarIndexRouteImport.update({
    id: '/course-calendar/',
    path: '/course-calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedWorkflowsVisualizationDemoRoute =
  AuthenticatedWorkflowsVisualizationDemoRouteImport.update({
    id: '/visualization-demo',
    path: '/visualization-demo',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsTestRoute =
  AuthenticatedWorkflowsTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsSchedulesRoute =
  AuthenticatedWorkflowsSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsQuickTestRoute =
  AuthenticatedWorkflowsQuickTestRouteImport.update({
    id: '/quick-test',
    path: '/quick-test',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsLogsRoute =
  AuthenticatedWorkflowsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsDefinitionsRoute =
  AuthenticatedWorkflowsDefinitionsRouteImport.update({
    id: '/definitions',
    path: '/definitions',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsCourseRestoreRoute =
  AuthenticatedWorkflowsCourseRestoreRouteImport.update({
    id: '/course-restore',
    path: '/course-restore',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedTasksSyncRoute = AuthenticatedTasksSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedTasksSettingsRoute =
  AuthenticatedTasksSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedSystemConfigTermRoute =
  AuthenticatedSystemConfigTermRouteImport.update({
    id: '/term',
    path: '/term',
    getParentRoute: () => AuthenticatedSystemConfigRouteRoute,
  } as any)
const AuthenticatedSystemConfigSyncRoute =
  AuthenticatedSystemConfigSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedSystemConfigRouteRoute,
  } as any)
const AuthenticatedSystemConfigCourseRoute =
  AuthenticatedSystemConfigCourseRouteImport.update({
    id: '/course',
    path: '/course',
    getParentRoute: () => AuthenticatedSystemConfigRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRbacUsersRoute = AuthenticatedRbacUsersRouteImport.update({
  id: '/rbac/users',
  path: '/rbac/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRbacRolesRoute = AuthenticatedRbacRolesRouteImport.update({
  id: '/rbac/roles',
  path: '/rbac/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRbacPermissionsRoute =
  AuthenticatedRbacPermissionsRouteImport.update({
    id: '/rbac/permissions',
    path: '/rbac/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRbacMenusRoute = AuthenticatedRbacMenusRouteImport.update({
  id: '/rbac/menus',
  path: '/rbac/menus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataQueryTeachingClassRoute =
  AuthenticatedDataQueryTeachingClassRouteImport.update({
    id: '/teaching-class',
    path: '/teaching-class',
    getParentRoute: () => AuthenticatedDataQueryRoute,
  } as any)
const AuthenticatedDataQueryCourseStatsTreeRoute =
  AuthenticatedDataQueryCourseStatsTreeRouteImport.update({
    id: '/course-stats-tree',
    path: '/course-stats-tree',
    getParentRoute: () => AuthenticatedDataQueryRoute,
  } as any)
const AuthenticatedDataQueryCourseStatsRoute =
  AuthenticatedDataQueryCourseStatsRouteImport.update({
    id: '/course-stats',
    path: '/course-stats',
    getParentRoute: () => AuthenticatedDataQueryRoute,
  } as any)
const AuthenticatedDataQueryAbsentHistoryRoute =
  AuthenticatedDataQueryAbsentHistoryRouteImport.update({
    id: '/absent-history',
    path: '/absent-history',
    getParentRoute: () => AuthenticatedDataQueryRoute,
  } as any)
const AuthenticatedCoursesSettingsRoute =
  AuthenticatedCoursesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const AuthenticatedCoursesScheduleRoute =
  AuthenticatedCoursesScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const AuthenticatedCourseCalendarStudentRoute =
  AuthenticatedCourseCalendarStudentRouteImport.update({
    id: '/course-calendar/student',
    path: '/course-calendar/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceStudentsRoute =
  AuthenticatedAttendanceStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceStudentStatsRoute =
  AuthenticatedAttendanceStudentStatsRouteImport.update({
    id: '/student-stats',
    path: '/student-stats',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceRankingsRoute =
  AuthenticatedAttendanceRankingsRouteImport.update({
    id: '/rankings',
    path: '/rankings',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceOverviewRoute =
  AuthenticatedAttendanceOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceFailedLogsRoute =
  AuthenticatedAttendanceFailedLogsRouteImport.update({
    id: '/failed-logs',
    path: '/failed-logs',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceCoursesRoute =
  AuthenticatedAttendanceCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceCourseStatisticsRoute =
  AuthenticatedAttendanceCourseStatisticsRouteImport.update({
    id: '/course-statistics',
    path: '/course-statistics',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedAttendanceAnalyticsRoute =
  AuthenticatedAttendanceAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAttendanceRoute,
  } as any)
const AuthenticatedWorkflowsInstancesIndexRoute =
  AuthenticatedWorkflowsInstancesIndexRouteImport.update({
    id: '/instances/',
    path: '/instances/',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsDefinitionsIndexRoute =
  AuthenticatedWorkflowsDefinitionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkflowsDefinitionsRoute,
  } as any)
const AuthenticatedWorkflowsInstancesInstanceIdRoute =
  AuthenticatedWorkflowsInstancesInstanceIdRouteImport.update({
    id: '/instances/$instanceId',
    path: '/instances/$instanceId',
    getParentRoute: () => AuthenticatedWorkflowsRouteRoute,
  } as any)
const AuthenticatedWorkflowsDefinitionsDefinitionIdRoute =
  AuthenticatedWorkflowsDefinitionsDefinitionIdRouteImport.update({
    id: '/$definitionId',
    path: '/$definitionId',
    getParentRoute: () => AuthenticatedWorkflowsDefinitionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/system-config': typeof AuthenticatedSystemConfigRouteRouteWithChildren
  '/workflows': typeof AuthenticatedWorkflowsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/callback': typeof authCallbackRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/basic-management': typeof AuthenticatedBasicManagementRoute
  '/course-reschedule': typeof AuthenticatedCourseRescheduleRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-query': typeof AuthenticatedDataQueryRouteWithChildren
  '/permission-debug': typeof AuthenticatedPermissionDebugRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRoute
  '/user-debug': typeof AuthenticatedUserDebugRoute
  '/wps-drive': typeof AuthenticatedWpsDriveRoute
  '/': typeof AuthenticatedIndexRoute
  '/attendance/analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/attendance/course-statistics': typeof AuthenticatedAttendanceCourseStatisticsRoute
  '/attendance/courses': typeof AuthenticatedAttendanceCoursesRoute
  '/attendance/failed-logs': typeof AuthenticatedAttendanceFailedLogsRoute
  '/attendance/overview': typeof AuthenticatedAttendanceOverviewRoute
  '/attendance/rankings': typeof AuthenticatedAttendanceRankingsRoute
  '/attendance/student-stats': typeof AuthenticatedAttendanceStudentStatsRoute
  '/attendance/students': typeof AuthenticatedAttendanceStudentsRoute
  '/course-calendar/student': typeof AuthenticatedCourseCalendarStudentRoute
  '/courses/schedule': typeof AuthenticatedCoursesScheduleRoute
  '/courses/settings': typeof AuthenticatedCoursesSettingsRoute
  '/data-query/absent-history': typeof AuthenticatedDataQueryAbsentHistoryRoute
  '/data-query/course-stats': typeof AuthenticatedDataQueryCourseStatsRoute
  '/data-query/course-stats-tree': typeof AuthenticatedDataQueryCourseStatsTreeRoute
  '/data-query/teaching-class': typeof AuthenticatedDataQueryTeachingClassRoute
  '/rbac/menus': typeof AuthenticatedRbacMenusRoute
  '/rbac/permissions': typeof AuthenticatedRbacPermissionsRoute
  '/rbac/roles': typeof AuthenticatedRbacRolesRoute
  '/rbac/users': typeof AuthenticatedRbacUsersRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/system-config/course': typeof AuthenticatedSystemConfigCourseRoute
  '/system-config/sync': typeof AuthenticatedSystemConfigSyncRoute
  '/system-config/term': typeof AuthenticatedSystemConfigTermRoute
  '/tasks/settings': typeof AuthenticatedTasksSettingsRoute
  '/tasks/sync': typeof AuthenticatedTasksSyncRoute
  '/workflows/course-restore': typeof AuthenticatedWorkflowsCourseRestoreRoute
  '/workflows/definitions': typeof AuthenticatedWorkflowsDefinitionsRouteWithChildren
  '/workflows/logs': typeof AuthenticatedWorkflowsLogsRoute
  '/workflows/quick-test': typeof AuthenticatedWorkflowsQuickTestRoute
  '/workflows/schedules': typeof AuthenticatedWorkflowsSchedulesRoute
  '/workflows/test': typeof AuthenticatedWorkflowsTestRoute
  '/workflows/visualization-demo': typeof AuthenticatedWorkflowsVisualizationDemoRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/course-calendar': typeof AuthenticatedCourseCalendarIndexRoute
  '/data-query/': typeof AuthenticatedDataQueryIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/system-config/': typeof AuthenticatedSystemConfigIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/workflows/definitions/$definitionId': typeof AuthenticatedWorkflowsDefinitionsDefinitionIdRoute
  '/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  '/workflows/definitions/': typeof AuthenticatedWorkflowsDefinitionsIndexRoute
  '/workflows/instances': typeof AuthenticatedWorkflowsInstancesIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/callback': typeof authCallbackRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/basic-management': typeof AuthenticatedBasicManagementRoute
  '/course-reschedule': typeof AuthenticatedCourseRescheduleRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/permission-debug': typeof AuthenticatedPermissionDebugRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/user-debug': typeof AuthenticatedUserDebugRoute
  '/wps-drive': typeof AuthenticatedWpsDriveRoute
  '/': typeof AuthenticatedIndexRoute
  '/attendance/analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/attendance/course-statistics': typeof AuthenticatedAttendanceCourseStatisticsRoute
  '/attendance/courses': typeof AuthenticatedAttendanceCoursesRoute
  '/attendance/failed-logs': typeof AuthenticatedAttendanceFailedLogsRoute
  '/attendance/overview': typeof AuthenticatedAttendanceOverviewRoute
  '/attendance/rankings': typeof AuthenticatedAttendanceRankingsRoute
  '/attendance/student-stats': typeof AuthenticatedAttendanceStudentStatsRoute
  '/attendance/students': typeof AuthenticatedAttendanceStudentsRoute
  '/course-calendar/student': typeof AuthenticatedCourseCalendarStudentRoute
  '/courses/schedule': typeof AuthenticatedCoursesScheduleRoute
  '/courses/settings': typeof AuthenticatedCoursesSettingsRoute
  '/data-query/absent-history': typeof AuthenticatedDataQueryAbsentHistoryRoute
  '/data-query/course-stats': typeof AuthenticatedDataQueryCourseStatsRoute
  '/data-query/course-stats-tree': typeof AuthenticatedDataQueryCourseStatsTreeRoute
  '/data-query/teaching-class': typeof AuthenticatedDataQueryTeachingClassRoute
  '/rbac/menus': typeof AuthenticatedRbacMenusRoute
  '/rbac/permissions': typeof AuthenticatedRbacPermissionsRoute
  '/rbac/roles': typeof AuthenticatedRbacRolesRoute
  '/rbac/users': typeof AuthenticatedRbacUsersRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/system-config/course': typeof AuthenticatedSystemConfigCourseRoute
  '/system-config/sync': typeof AuthenticatedSystemConfigSyncRoute
  '/system-config/term': typeof AuthenticatedSystemConfigTermRoute
  '/tasks/settings': typeof AuthenticatedTasksSettingsRoute
  '/tasks/sync': typeof AuthenticatedTasksSyncRoute
  '/workflows/course-restore': typeof AuthenticatedWorkflowsCourseRestoreRoute
  '/workflows/logs': typeof AuthenticatedWorkflowsLogsRoute
  '/workflows/quick-test': typeof AuthenticatedWorkflowsQuickTestRoute
  '/workflows/schedules': typeof AuthenticatedWorkflowsSchedulesRoute
  '/workflows/test': typeof AuthenticatedWorkflowsTestRoute
  '/workflows/visualization-demo': typeof AuthenticatedWorkflowsVisualizationDemoRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/course-calendar': typeof AuthenticatedCourseCalendarIndexRoute
  '/data-query': typeof AuthenticatedDataQueryIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/system-config': typeof AuthenticatedSystemConfigIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/workflows/definitions/$definitionId': typeof AuthenticatedWorkflowsDefinitionsDefinitionIdRoute
  '/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  '/workflows/definitions': typeof AuthenticatedWorkflowsDefinitionsIndexRoute
  '/workflows/instances': typeof AuthenticatedWorkflowsInstancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/system-config': typeof AuthenticatedSystemConfigRouteRouteWithChildren
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/callback': typeof authCallbackRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRouteWithChildren
  '/_authenticated/basic-management': typeof AuthenticatedBasicManagementRoute
  '/_authenticated/course-reschedule': typeof AuthenticatedCourseRescheduleRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-query': typeof AuthenticatedDataQueryRouteWithChildren
  '/_authenticated/permission-debug': typeof AuthenticatedPermissionDebugRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute
  '/_authenticated/user-debug': typeof AuthenticatedUserDebugRoute
  '/_authenticated/wps-drive': typeof AuthenticatedWpsDriveRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/attendance/analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/_authenticated/attendance/course-statistics': typeof AuthenticatedAttendanceCourseStatisticsRoute
  '/_authenticated/attendance/courses': typeof AuthenticatedAttendanceCoursesRoute
  '/_authenticated/attendance/failed-logs': typeof AuthenticatedAttendanceFailedLogsRoute
  '/_authenticated/attendance/overview': typeof AuthenticatedAttendanceOverviewRoute
  '/_authenticated/attendance/rankings': typeof AuthenticatedAttendanceRankingsRoute
  '/_authenticated/attendance/student-stats': typeof AuthenticatedAttendanceStudentStatsRoute
  '/_authenticated/attendance/students': typeof AuthenticatedAttendanceStudentsRoute
  '/_authenticated/course-calendar/student': typeof AuthenticatedCourseCalendarStudentRoute
  '/_authenticated/courses/schedule': typeof AuthenticatedCoursesScheduleRoute
  '/_authenticated/courses/settings': typeof AuthenticatedCoursesSettingsRoute
  '/_authenticated/data-query/absent-history': typeof AuthenticatedDataQueryAbsentHistoryRoute
  '/_authenticated/data-query/course-stats': typeof AuthenticatedDataQueryCourseStatsRoute
  '/_authenticated/data-query/course-stats-tree': typeof AuthenticatedDataQueryCourseStatsTreeRoute
  '/_authenticated/data-query/teaching-class': typeof AuthenticatedDataQueryTeachingClassRoute
  '/_authenticated/rbac/menus': typeof AuthenticatedRbacMenusRoute
  '/_authenticated/rbac/permissions': typeof AuthenticatedRbacPermissionsRoute
  '/_authenticated/rbac/roles': typeof AuthenticatedRbacRolesRoute
  '/_authenticated/rbac/users': typeof AuthenticatedRbacUsersRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/system-config/course': typeof AuthenticatedSystemConfigCourseRoute
  '/_authenticated/system-config/sync': typeof AuthenticatedSystemConfigSyncRoute
  '/_authenticated/system-config/term': typeof AuthenticatedSystemConfigTermRoute
  '/_authenticated/tasks/settings': typeof AuthenticatedTasksSettingsRoute
  '/_authenticated/tasks/sync': typeof AuthenticatedTasksSyncRoute
  '/_authenticated/workflows/course-restore': typeof AuthenticatedWorkflowsCourseRestoreRoute
  '/_authenticated/workflows/definitions': typeof AuthenticatedWorkflowsDefinitionsRouteWithChildren
  '/_authenticated/workflows/logs': typeof AuthenticatedWorkflowsLogsRoute
  '/_authenticated/workflows/quick-test': typeof AuthenticatedWorkflowsQuickTestRoute
  '/_authenticated/workflows/schedules': typeof AuthenticatedWorkflowsSchedulesRoute
  '/_authenticated/workflows/test': typeof AuthenticatedWorkflowsTestRoute
  '/_authenticated/workflows/visualization-demo': typeof AuthenticatedWorkflowsVisualizationDemoRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/course-calendar/': typeof AuthenticatedCourseCalendarIndexRoute
  '/_authenticated/data-query/': typeof AuthenticatedDataQueryIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/system-config/': typeof AuthenticatedSystemConfigIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/_authenticated/workflows/definitions/$definitionId': typeof AuthenticatedWorkflowsDefinitionsDefinitionIdRoute
  '/_authenticated/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  '/_authenticated/workflows/definitions/': typeof AuthenticatedWorkflowsDefinitionsIndexRoute
  '/_authenticated/workflows/instances/': typeof AuthenticatedWorkflowsInstancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/system-config'
    | '/workflows'
    | '/clerk/'
    | '/callback'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin'
    | '/analytics'
    | '/attendance'
    | '/basic-management'
    | '/course-reschedule'
    | '/courses'
    | '/dashboard'
    | '/data-query'
    | '/permission-debug'
    | '/students'
    | '/tasks'
    | '/teachers'
    | '/user-debug'
    | '/wps-drive'
    | '/'
    | '/attendance/analytics'
    | '/attendance/course-statistics'
    | '/attendance/courses'
    | '/attendance/failed-logs'
    | '/attendance/overview'
    | '/attendance/rankings'
    | '/attendance/student-stats'
    | '/attendance/students'
    | '/course-calendar/student'
    | '/courses/schedule'
    | '/courses/settings'
    | '/data-query/absent-history'
    | '/data-query/course-stats'
    | '/data-query/course-stats-tree'
    | '/data-query/teaching-class'
    | '/rbac/menus'
    | '/rbac/permissions'
    | '/rbac/roles'
    | '/rbac/users'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/system-config/course'
    | '/system-config/sync'
    | '/system-config/term'
    | '/tasks/settings'
    | '/tasks/sync'
    | '/workflows/course-restore'
    | '/workflows/definitions'
    | '/workflows/logs'
    | '/workflows/quick-test'
    | '/workflows/schedules'
    | '/workflows/test'
    | '/workflows/visualization-demo'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/attendance/'
    | '/chats'
    | '/course-calendar'
    | '/data-query/'
    | '/help-center'
    | '/settings/'
    | '/system-config/'
    | '/tasks/'
    | '/users'
    | '/workflows/'
    | '/workflows/definitions/$definitionId'
    | '/workflows/instances/$instanceId'
    | '/workflows/definitions/'
    | '/workflows/instances'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/callback'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin'
    | '/analytics'
    | '/basic-management'
    | '/course-reschedule'
    | '/courses'
    | '/dashboard'
    | '/permission-debug'
    | '/students'
    | '/teachers'
    | '/user-debug'
    | '/wps-drive'
    | '/'
    | '/attendance/analytics'
    | '/attendance/course-statistics'
    | '/attendance/courses'
    | '/attendance/failed-logs'
    | '/attendance/overview'
    | '/attendance/rankings'
    | '/attendance/student-stats'
    | '/attendance/students'
    | '/course-calendar/student'
    | '/courses/schedule'
    | '/courses/settings'
    | '/data-query/absent-history'
    | '/data-query/course-stats'
    | '/data-query/course-stats-tree'
    | '/data-query/teaching-class'
    | '/rbac/menus'
    | '/rbac/permissions'
    | '/rbac/roles'
    | '/rbac/users'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/system-config/course'
    | '/system-config/sync'
    | '/system-config/term'
    | '/tasks/settings'
    | '/tasks/sync'
    | '/workflows/course-restore'
    | '/workflows/logs'
    | '/workflows/quick-test'
    | '/workflows/schedules'
    | '/workflows/test'
    | '/workflows/visualization-demo'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/attendance'
    | '/chats'
    | '/course-calendar'
    | '/data-query'
    | '/help-center'
    | '/settings'
    | '/system-config'
    | '/tasks'
    | '/users'
    | '/workflows'
    | '/workflows/definitions/$definitionId'
    | '/workflows/instances/$instanceId'
    | '/workflows/definitions'
    | '/workflows/instances'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/_authenticated/system-config'
    | '/_authenticated/workflows'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/callback'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/attendance'
    | '/_authenticated/basic-management'
    | '/_authenticated/course-reschedule'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-query'
    | '/_authenticated/permission-debug'
    | '/_authenticated/students'
    | '/_authenticated/tasks'
    | '/_authenticated/teachers'
    | '/_authenticated/user-debug'
    | '/_authenticated/wps-drive'
    | '/_authenticated/'
    | '/_authenticated/attendance/analytics'
    | '/_authenticated/attendance/course-statistics'
    | '/_authenticated/attendance/courses'
    | '/_authenticated/attendance/failed-logs'
    | '/_authenticated/attendance/overview'
    | '/_authenticated/attendance/rankings'
    | '/_authenticated/attendance/student-stats'
    | '/_authenticated/attendance/students'
    | '/_authenticated/course-calendar/student'
    | '/_authenticated/courses/schedule'
    | '/_authenticated/courses/settings'
    | '/_authenticated/data-query/absent-history'
    | '/_authenticated/data-query/course-stats'
    | '/_authenticated/data-query/course-stats-tree'
    | '/_authenticated/data-query/teaching-class'
    | '/_authenticated/rbac/menus'
    | '/_authenticated/rbac/permissions'
    | '/_authenticated/rbac/roles'
    | '/_authenticated/rbac/users'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/system-config/course'
    | '/_authenticated/system-config/sync'
    | '/_authenticated/system-config/term'
    | '/_authenticated/tasks/settings'
    | '/_authenticated/tasks/sync'
    | '/_authenticated/workflows/course-restore'
    | '/_authenticated/workflows/definitions'
    | '/_authenticated/workflows/logs'
    | '/_authenticated/workflows/quick-test'
    | '/_authenticated/workflows/schedules'
    | '/_authenticated/workflows/test'
    | '/_authenticated/workflows/visualization-demo'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/attendance/'
    | '/_authenticated/chats/'
    | '/_authenticated/course-calendar/'
    | '/_authenticated/data-query/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/system-config/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/workflows/'
    | '/_authenticated/workflows/definitions/$definitionId'
    | '/_authenticated/workflows/instances/$instanceId'
    | '/_authenticated/workflows/definitions/'
    | '/_authenticated/workflows/instances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authCallbackRoute: typeof authCallbackRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wps-drive': {
      id: '/_authenticated/wps-drive'
      path: '/wps-drive'
      fullPath: '/wps-drive'
      preLoaderRoute: typeof AuthenticatedWpsDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-debug': {
      id: '/_authenticated/user-debug'
      path: '/user-debug'
      fullPath: '/user-debug'
      preLoaderRoute: typeof AuthenticatedUserDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permission-debug': {
      id: '/_authenticated/permission-debug'
      path: '/permission-debug'
      fullPath: '/permission-debug'
      preLoaderRoute: typeof AuthenticatedPermissionDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-query': {
      id: '/_authenticated/data-query'
      path: '/data-query'
      fullPath: '/data-query'
      preLoaderRoute: typeof AuthenticatedDataQueryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-reschedule': {
      id: '/_authenticated/course-reschedule'
      path: '/course-reschedule'
      fullPath: '/course-reschedule'
      preLoaderRoute: typeof AuthenticatedCourseRescheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/basic-management': {
      id: '/_authenticated/basic-management'
      path: '/basic-management'
      fullPath: '/basic-management'
      preLoaderRoute: typeof AuthenticatedBasicManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/callback': {
      id: '/(auth)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof authCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-config': {
      id: '/_authenticated/system-config'
      path: '/system-config'
      fullPath: '/system-config'
      preLoaderRoute: typeof AuthenticatedSystemConfigRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/system-config/': {
      id: '/_authenticated/system-config/'
      path: '/'
      fullPath: '/system-config/'
      preLoaderRoute: typeof AuthenticatedSystemConfigIndexRouteImport
      parentRoute: typeof AuthenticatedSystemConfigRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-query/': {
      id: '/_authenticated/data-query/'
      path: '/'
      fullPath: '/data-query/'
      preLoaderRoute: typeof AuthenticatedDataQueryIndexRouteImport
      parentRoute: typeof AuthenticatedDataQueryRoute
    }
    '/_authenticated/course-calendar/': {
      id: '/_authenticated/course-calendar/'
      path: '/course-calendar'
      fullPath: '/course-calendar'
      preLoaderRoute: typeof AuthenticatedCourseCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/workflows/visualization-demo': {
      id: '/_authenticated/workflows/visualization-demo'
      path: '/visualization-demo'
      fullPath: '/workflows/visualization-demo'
      preLoaderRoute: typeof AuthenticatedWorkflowsVisualizationDemoRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/test': {
      id: '/_authenticated/workflows/test'
      path: '/test'
      fullPath: '/workflows/test'
      preLoaderRoute: typeof AuthenticatedWorkflowsTestRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/schedules': {
      id: '/_authenticated/workflows/schedules'
      path: '/schedules'
      fullPath: '/workflows/schedules'
      preLoaderRoute: typeof AuthenticatedWorkflowsSchedulesRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/quick-test': {
      id: '/_authenticated/workflows/quick-test'
      path: '/quick-test'
      fullPath: '/workflows/quick-test'
      preLoaderRoute: typeof AuthenticatedWorkflowsQuickTestRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/logs': {
      id: '/_authenticated/workflows/logs'
      path: '/logs'
      fullPath: '/workflows/logs'
      preLoaderRoute: typeof AuthenticatedWorkflowsLogsRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/definitions': {
      id: '/_authenticated/workflows/definitions'
      path: '/definitions'
      fullPath: '/workflows/definitions'
      preLoaderRoute: typeof AuthenticatedWorkflowsDefinitionsRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/course-restore': {
      id: '/_authenticated/workflows/course-restore'
      path: '/course-restore'
      fullPath: '/workflows/course-restore'
      preLoaderRoute: typeof AuthenticatedWorkflowsCourseRestoreRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/tasks/sync': {
      id: '/_authenticated/tasks/sync'
      path: '/sync'
      fullPath: '/tasks/sync'
      preLoaderRoute: typeof AuthenticatedTasksSyncRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/settings': {
      id: '/_authenticated/tasks/settings'
      path: '/settings'
      fullPath: '/tasks/settings'
      preLoaderRoute: typeof AuthenticatedTasksSettingsRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/system-config/term': {
      id: '/_authenticated/system-config/term'
      path: '/term'
      fullPath: '/system-config/term'
      preLoaderRoute: typeof AuthenticatedSystemConfigTermRouteImport
      parentRoute: typeof AuthenticatedSystemConfigRouteRoute
    }
    '/_authenticated/system-config/sync': {
      id: '/_authenticated/system-config/sync'
      path: '/sync'
      fullPath: '/system-config/sync'
      preLoaderRoute: typeof AuthenticatedSystemConfigSyncRouteImport
      parentRoute: typeof AuthenticatedSystemConfigRouteRoute
    }
    '/_authenticated/system-config/course': {
      id: '/_authenticated/system-config/course'
      path: '/course'
      fullPath: '/system-config/course'
      preLoaderRoute: typeof AuthenticatedSystemConfigCourseRouteImport
      parentRoute: typeof AuthenticatedSystemConfigRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/rbac/users': {
      id: '/_authenticated/rbac/users'
      path: '/rbac/users'
      fullPath: '/rbac/users'
      preLoaderRoute: typeof AuthenticatedRbacUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rbac/roles': {
      id: '/_authenticated/rbac/roles'
      path: '/rbac/roles'
      fullPath: '/rbac/roles'
      preLoaderRoute: typeof AuthenticatedRbacRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rbac/permissions': {
      id: '/_authenticated/rbac/permissions'
      path: '/rbac/permissions'
      fullPath: '/rbac/permissions'
      preLoaderRoute: typeof AuthenticatedRbacPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rbac/menus': {
      id: '/_authenticated/rbac/menus'
      path: '/rbac/menus'
      fullPath: '/rbac/menus'
      preLoaderRoute: typeof AuthenticatedRbacMenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-query/teaching-class': {
      id: '/_authenticated/data-query/teaching-class'
      path: '/teaching-class'
      fullPath: '/data-query/teaching-class'
      preLoaderRoute: typeof AuthenticatedDataQueryTeachingClassRouteImport
      parentRoute: typeof AuthenticatedDataQueryRoute
    }
    '/_authenticated/data-query/course-stats-tree': {
      id: '/_authenticated/data-query/course-stats-tree'
      path: '/course-stats-tree'
      fullPath: '/data-query/course-stats-tree'
      preLoaderRoute: typeof AuthenticatedDataQueryCourseStatsTreeRouteImport
      parentRoute: typeof AuthenticatedDataQueryRoute
    }
    '/_authenticated/data-query/course-stats': {
      id: '/_authenticated/data-query/course-stats'
      path: '/course-stats'
      fullPath: '/data-query/course-stats'
      preLoaderRoute: typeof AuthenticatedDataQueryCourseStatsRouteImport
      parentRoute: typeof AuthenticatedDataQueryRoute
    }
    '/_authenticated/data-query/absent-history': {
      id: '/_authenticated/data-query/absent-history'
      path: '/absent-history'
      fullPath: '/data-query/absent-history'
      preLoaderRoute: typeof AuthenticatedDataQueryAbsentHistoryRouteImport
      parentRoute: typeof AuthenticatedDataQueryRoute
    }
    '/_authenticated/courses/settings': {
      id: '/_authenticated/courses/settings'
      path: '/settings'
      fullPath: '/courses/settings'
      preLoaderRoute: typeof AuthenticatedCoursesSettingsRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/courses/schedule': {
      id: '/_authenticated/courses/schedule'
      path: '/schedule'
      fullPath: '/courses/schedule'
      preLoaderRoute: typeof AuthenticatedCoursesScheduleRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/course-calendar/student': {
      id: '/_authenticated/course-calendar/student'
      path: '/course-calendar/student'
      fullPath: '/course-calendar/student'
      preLoaderRoute: typeof AuthenticatedCourseCalendarStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/students': {
      id: '/_authenticated/attendance/students'
      path: '/students'
      fullPath: '/attendance/students'
      preLoaderRoute: typeof AuthenticatedAttendanceStudentsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/student-stats': {
      id: '/_authenticated/attendance/student-stats'
      path: '/student-stats'
      fullPath: '/attendance/student-stats'
      preLoaderRoute: typeof AuthenticatedAttendanceStudentStatsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/rankings': {
      id: '/_authenticated/attendance/rankings'
      path: '/rankings'
      fullPath: '/attendance/rankings'
      preLoaderRoute: typeof AuthenticatedAttendanceRankingsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/overview': {
      id: '/_authenticated/attendance/overview'
      path: '/overview'
      fullPath: '/attendance/overview'
      preLoaderRoute: typeof AuthenticatedAttendanceOverviewRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/failed-logs': {
      id: '/_authenticated/attendance/failed-logs'
      path: '/failed-logs'
      fullPath: '/attendance/failed-logs'
      preLoaderRoute: typeof AuthenticatedAttendanceFailedLogsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/courses': {
      id: '/_authenticated/attendance/courses'
      path: '/courses'
      fullPath: '/attendance/courses'
      preLoaderRoute: typeof AuthenticatedAttendanceCoursesRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/course-statistics': {
      id: '/_authenticated/attendance/course-statistics'
      path: '/course-statistics'
      fullPath: '/attendance/course-statistics'
      preLoaderRoute: typeof AuthenticatedAttendanceCourseStatisticsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/attendance/analytics': {
      id: '/_authenticated/attendance/analytics'
      path: '/analytics'
      fullPath: '/attendance/analytics'
      preLoaderRoute: typeof AuthenticatedAttendanceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAttendanceRoute
    }
    '/_authenticated/workflows/instances/': {
      id: '/_authenticated/workflows/instances/'
      path: '/instances'
      fullPath: '/workflows/instances'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/definitions/': {
      id: '/_authenticated/workflows/definitions/'
      path: '/'
      fullPath: '/workflows/definitions/'
      preLoaderRoute: typeof AuthenticatedWorkflowsDefinitionsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkflowsDefinitionsRoute
    }
    '/_authenticated/workflows/instances/$instanceId': {
      id: '/_authenticated/workflows/instances/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/workflows/instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRouteRoute
    }
    '/_authenticated/workflows/definitions/$definitionId': {
      id: '/_authenticated/workflows/definitions/$definitionId'
      path: '/$definitionId'
      fullPath: '/workflows/definitions/$definitionId'
      preLoaderRoute: typeof AuthenticatedWorkflowsDefinitionsDefinitionIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsDefinitionsRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSystemConfigRouteRouteChildren {
  AuthenticatedSystemConfigCourseRoute: typeof AuthenticatedSystemConfigCourseRoute
  AuthenticatedSystemConfigSyncRoute: typeof AuthenticatedSystemConfigSyncRoute
  AuthenticatedSystemConfigTermRoute: typeof AuthenticatedSystemConfigTermRoute
  AuthenticatedSystemConfigIndexRoute: typeof AuthenticatedSystemConfigIndexRoute
}

const AuthenticatedSystemConfigRouteRouteChildren: AuthenticatedSystemConfigRouteRouteChildren =
  {
    AuthenticatedSystemConfigCourseRoute: AuthenticatedSystemConfigCourseRoute,
    AuthenticatedSystemConfigSyncRoute: AuthenticatedSystemConfigSyncRoute,
    AuthenticatedSystemConfigTermRoute: AuthenticatedSystemConfigTermRoute,
    AuthenticatedSystemConfigIndexRoute: AuthenticatedSystemConfigIndexRoute,
  }

const AuthenticatedSystemConfigRouteRouteWithChildren =
  AuthenticatedSystemConfigRouteRoute._addFileChildren(
    AuthenticatedSystemConfigRouteRouteChildren,
  )

interface AuthenticatedWorkflowsDefinitionsRouteChildren {
  AuthenticatedWorkflowsDefinitionsDefinitionIdRoute: typeof AuthenticatedWorkflowsDefinitionsDefinitionIdRoute
  AuthenticatedWorkflowsDefinitionsIndexRoute: typeof AuthenticatedWorkflowsDefinitionsIndexRoute
}

const AuthenticatedWorkflowsDefinitionsRouteChildren: AuthenticatedWorkflowsDefinitionsRouteChildren =
  {
    AuthenticatedWorkflowsDefinitionsDefinitionIdRoute:
      AuthenticatedWorkflowsDefinitionsDefinitionIdRoute,
    AuthenticatedWorkflowsDefinitionsIndexRoute:
      AuthenticatedWorkflowsDefinitionsIndexRoute,
  }

const AuthenticatedWorkflowsDefinitionsRouteWithChildren =
  AuthenticatedWorkflowsDefinitionsRoute._addFileChildren(
    AuthenticatedWorkflowsDefinitionsRouteChildren,
  )

interface AuthenticatedWorkflowsRouteRouteChildren {
  AuthenticatedWorkflowsCourseRestoreRoute: typeof AuthenticatedWorkflowsCourseRestoreRoute
  AuthenticatedWorkflowsDefinitionsRoute: typeof AuthenticatedWorkflowsDefinitionsRouteWithChildren
  AuthenticatedWorkflowsLogsRoute: typeof AuthenticatedWorkflowsLogsRoute
  AuthenticatedWorkflowsQuickTestRoute: typeof AuthenticatedWorkflowsQuickTestRoute
  AuthenticatedWorkflowsSchedulesRoute: typeof AuthenticatedWorkflowsSchedulesRoute
  AuthenticatedWorkflowsTestRoute: typeof AuthenticatedWorkflowsTestRoute
  AuthenticatedWorkflowsVisualizationDemoRoute: typeof AuthenticatedWorkflowsVisualizationDemoRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
  AuthenticatedWorkflowsInstancesInstanceIdRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  AuthenticatedWorkflowsInstancesIndexRoute: typeof AuthenticatedWorkflowsInstancesIndexRoute
}

const AuthenticatedWorkflowsRouteRouteChildren: AuthenticatedWorkflowsRouteRouteChildren =
  {
    AuthenticatedWorkflowsCourseRestoreRoute:
      AuthenticatedWorkflowsCourseRestoreRoute,
    AuthenticatedWorkflowsDefinitionsRoute:
      AuthenticatedWorkflowsDefinitionsRouteWithChildren,
    AuthenticatedWorkflowsLogsRoute: AuthenticatedWorkflowsLogsRoute,
    AuthenticatedWorkflowsQuickTestRoute: AuthenticatedWorkflowsQuickTestRoute,
    AuthenticatedWorkflowsSchedulesRoute: AuthenticatedWorkflowsSchedulesRoute,
    AuthenticatedWorkflowsTestRoute: AuthenticatedWorkflowsTestRoute,
    AuthenticatedWorkflowsVisualizationDemoRoute:
      AuthenticatedWorkflowsVisualizationDemoRoute,
    AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
    AuthenticatedWorkflowsInstancesInstanceIdRoute:
      AuthenticatedWorkflowsInstancesInstanceIdRoute,
    AuthenticatedWorkflowsInstancesIndexRoute:
      AuthenticatedWorkflowsInstancesIndexRoute,
  }

const AuthenticatedWorkflowsRouteRouteWithChildren =
  AuthenticatedWorkflowsRouteRoute._addFileChildren(
    AuthenticatedWorkflowsRouteRouteChildren,
  )

interface AuthenticatedAttendanceRouteChildren {
  AuthenticatedAttendanceAnalyticsRoute: typeof AuthenticatedAttendanceAnalyticsRoute
  AuthenticatedAttendanceCourseStatisticsRoute: typeof AuthenticatedAttendanceCourseStatisticsRoute
  AuthenticatedAttendanceCoursesRoute: typeof AuthenticatedAttendanceCoursesRoute
  AuthenticatedAttendanceFailedLogsRoute: typeof AuthenticatedAttendanceFailedLogsRoute
  AuthenticatedAttendanceOverviewRoute: typeof AuthenticatedAttendanceOverviewRoute
  AuthenticatedAttendanceRankingsRoute: typeof AuthenticatedAttendanceRankingsRoute
  AuthenticatedAttendanceStudentStatsRoute: typeof AuthenticatedAttendanceStudentStatsRoute
  AuthenticatedAttendanceStudentsRoute: typeof AuthenticatedAttendanceStudentsRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
}

const AuthenticatedAttendanceRouteChildren: AuthenticatedAttendanceRouteChildren =
  {
    AuthenticatedAttendanceAnalyticsRoute:
      AuthenticatedAttendanceAnalyticsRoute,
    AuthenticatedAttendanceCourseStatisticsRoute:
      AuthenticatedAttendanceCourseStatisticsRoute,
    AuthenticatedAttendanceCoursesRoute: AuthenticatedAttendanceCoursesRoute,
    AuthenticatedAttendanceFailedLogsRoute:
      AuthenticatedAttendanceFailedLogsRoute,
    AuthenticatedAttendanceOverviewRoute: AuthenticatedAttendanceOverviewRoute,
    AuthenticatedAttendanceRankingsRoute: AuthenticatedAttendanceRankingsRoute,
    AuthenticatedAttendanceStudentStatsRoute:
      AuthenticatedAttendanceStudentStatsRoute,
    AuthenticatedAttendanceStudentsRoute: AuthenticatedAttendanceStudentsRoute,
    AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  }

const AuthenticatedAttendanceRouteWithChildren =
  AuthenticatedAttendanceRoute._addFileChildren(
    AuthenticatedAttendanceRouteChildren,
  )

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesScheduleRoute: typeof AuthenticatedCoursesScheduleRoute
  AuthenticatedCoursesSettingsRoute: typeof AuthenticatedCoursesSettingsRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesScheduleRoute: AuthenticatedCoursesScheduleRoute,
  AuthenticatedCoursesSettingsRoute: AuthenticatedCoursesSettingsRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedDataQueryRouteChildren {
  AuthenticatedDataQueryAbsentHistoryRoute: typeof AuthenticatedDataQueryAbsentHistoryRoute
  AuthenticatedDataQueryCourseStatsRoute: typeof AuthenticatedDataQueryCourseStatsRoute
  AuthenticatedDataQueryCourseStatsTreeRoute: typeof AuthenticatedDataQueryCourseStatsTreeRoute
  AuthenticatedDataQueryTeachingClassRoute: typeof AuthenticatedDataQueryTeachingClassRoute
  AuthenticatedDataQueryIndexRoute: typeof AuthenticatedDataQueryIndexRoute
}

const AuthenticatedDataQueryRouteChildren: AuthenticatedDataQueryRouteChildren =
  {
    AuthenticatedDataQueryAbsentHistoryRoute:
      AuthenticatedDataQueryAbsentHistoryRoute,
    AuthenticatedDataQueryCourseStatsRoute:
      AuthenticatedDataQueryCourseStatsRoute,
    AuthenticatedDataQueryCourseStatsTreeRoute:
      AuthenticatedDataQueryCourseStatsTreeRoute,
    AuthenticatedDataQueryTeachingClassRoute:
      AuthenticatedDataQueryTeachingClassRoute,
    AuthenticatedDataQueryIndexRoute: AuthenticatedDataQueryIndexRoute,
  }

const AuthenticatedDataQueryRouteWithChildren =
  AuthenticatedDataQueryRoute._addFileChildren(
    AuthenticatedDataQueryRouteChildren,
  )

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksSettingsRoute: typeof AuthenticatedTasksSettingsRoute
  AuthenticatedTasksSyncRoute: typeof AuthenticatedTasksSyncRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksSettingsRoute: AuthenticatedTasksSettingsRoute,
  AuthenticatedTasksSyncRoute: AuthenticatedTasksSyncRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSystemConfigRouteRoute: typeof AuthenticatedSystemConfigRouteRouteWithChildren
  AuthenticatedWorkflowsRouteRoute: typeof AuthenticatedWorkflowsRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRouteWithChildren
  AuthenticatedBasicManagementRoute: typeof AuthenticatedBasicManagementRoute
  AuthenticatedCourseRescheduleRoute: typeof AuthenticatedCourseRescheduleRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataQueryRoute: typeof AuthenticatedDataQueryRouteWithChildren
  AuthenticatedPermissionDebugRoute: typeof AuthenticatedPermissionDebugRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute
  AuthenticatedUserDebugRoute: typeof AuthenticatedUserDebugRoute
  AuthenticatedWpsDriveRoute: typeof AuthenticatedWpsDriveRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCourseCalendarStudentRoute: typeof AuthenticatedCourseCalendarStudentRoute
  AuthenticatedRbacMenusRoute: typeof AuthenticatedRbacMenusRoute
  AuthenticatedRbacPermissionsRoute: typeof AuthenticatedRbacPermissionsRoute
  AuthenticatedRbacRolesRoute: typeof AuthenticatedRbacRolesRoute
  AuthenticatedRbacUsersRoute: typeof AuthenticatedRbacUsersRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCourseCalendarIndexRoute: typeof AuthenticatedCourseCalendarIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSystemConfigRouteRoute:
    AuthenticatedSystemConfigRouteRouteWithChildren,
  AuthenticatedWorkflowsRouteRoute:
    AuthenticatedWorkflowsRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRouteWithChildren,
  AuthenticatedBasicManagementRoute: AuthenticatedBasicManagementRoute,
  AuthenticatedCourseRescheduleRoute: AuthenticatedCourseRescheduleRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataQueryRoute: AuthenticatedDataQueryRouteWithChildren,
  AuthenticatedPermissionDebugRoute: AuthenticatedPermissionDebugRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedUserDebugRoute: AuthenticatedUserDebugRoute,
  AuthenticatedWpsDriveRoute: AuthenticatedWpsDriveRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCourseCalendarStudentRoute:
    AuthenticatedCourseCalendarStudentRoute,
  AuthenticatedRbacMenusRoute: AuthenticatedRbacMenusRoute,
  AuthenticatedRbacPermissionsRoute: AuthenticatedRbacPermissionsRoute,
  AuthenticatedRbacRolesRoute: AuthenticatedRbacRolesRoute,
  AuthenticatedRbacUsersRoute: AuthenticatedRbacUsersRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCourseCalendarIndexRoute: AuthenticatedCourseCalendarIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authCallbackRoute: authCallbackRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
