export interface OpenApiDocument {
  paths?: Record<string, Record<string, OpenApiOperation>>;
}

export interface OpenApiOperation {
  operationId?: string;
  responses?: Record<string, OpenApiResponse>;
}

export interface OpenApiResponse {
  content?: {
    'application/json'?: {
      schema?: JsonSchemaObject;
    };
  };
}

export interface JsonSchemaObject {
  type?: string | string[];
  const?: unknown;
  enum?: unknown[];
  properties?: Record<string, JsonSchemaObject>;
  required?: string[];
  items?: JsonSchemaObject;
  additionalProperties?: boolean | JsonSchemaObject;
  oneOf?: JsonSchemaObject[];
  anyOf?: JsonSchemaObject[];
}

const HTTP_METHODS = new Set([
  'get',
  'post',
  'put',
  'delete',
  'patch',
  'head',
  'options'
]);

function toPascalCase(value: string): string {
  return value
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/^[a-z]/, (char) => char.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

function toCamelCase(value: string): string {
  const pascal = toPascalCase(value);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function literalType(value: unknown): string {
  if (typeof value === 'string') {
    return JSON.stringify(value);
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (value === null) {
    return 'null';
  }
  return 'unknown';
}

function schemaToType(schema: JsonSchemaObject | undefined, indent = 0): string {
  if (!schema) {
    return 'unknown';
  }

  if (schema.const !== undefined) {
    return literalType(schema.const);
  }

  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum.map(literalType).join(' | ');
  }

  if (Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
    return schema.oneOf.map((entry) => schemaToType(entry, indent)).join(' | ');
  }

  if (Array.isArray(schema.anyOf) && schema.anyOf.length > 0) {
    return schema.anyOf.map((entry) => schemaToType(entry, indent)).join(' | ');
  }

  const type = Array.isArray(schema.type)
    ? schema.type.filter((entry) => entry !== 'null')[0]
    : schema.type;

  switch (type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array':
      return `${schemaToType(schema.items, indent)}[]`;
    case 'object':
    default:
      return objectSchemaToType(schema, indent);
  }
}

function objectSchemaToType(schema: JsonSchemaObject, indent: number): string {
  const properties = schema.properties || {};
  const required = new Set(schema.required || []);

  if (Object.keys(properties).length === 0) {
    if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
      return `Record<string, ${schemaToType(schema.additionalProperties, indent)}>`;
    }
    return 'Record<string, unknown>';
  }

  const pad = ' '.repeat(indent);
  const innerPad = ' '.repeat(indent + 2);
  const lines = Object.entries(properties).map(([key, propertySchema]) => {
    const optional = required.has(key) ? '' : '?';
    return `${innerPad}${key}${optional}: ${schemaToType(propertySchema, indent + 2)};`;
  });

  return `{\n${lines.join('\n')}\n${pad}}`;
}

function responseSchema(operation: OpenApiOperation): JsonSchemaObject | undefined {
  const responses = operation.responses || {};
  const status =
    Object.keys(responses).find((candidate) => candidate.startsWith('2')) ||
    Object.keys(responses)[0];
  return status
    ? responses[status]?.content?.['application/json']?.schema
    : undefined;
}

export function generateTypedClient(document: OpenApiDocument): string {
  const lines: string[] = [
    '// Generated by stratix openapi client. Do not edit by hand.',
    ''
  ];

  const operations: Array<{
    method: string;
    path: string;
    operationId: string;
    responseType: string;
  }> = [];

  for (const [routePath, pathItem] of Object.entries(document.paths || {})) {
    for (const [method, operation] of Object.entries(pathItem || {})) {
      if (!HTTP_METHODS.has(method.toLowerCase()) || !operation.operationId) {
        continue;
      }

      const responseType = `${toPascalCase(operation.operationId)}Response`;
      operations.push({
        method: method.toUpperCase(),
        path: routePath,
        operationId: operation.operationId,
        responseType
      });

      lines.push(
        `export interface ${responseType} ${schemaToType(responseSchema(operation), 0)}`,
        ''
      );
    }
  }

  for (const operation of operations) {
    lines.push(
      `export async function ${toCamelCase(operation.operationId)}(`,
      '  baseUrl: string,',
      '  init: RequestInit = {}',
      `): Promise<${operation.responseType}> {`,
      `  const response = await fetch(\`\${baseUrl}${operation.path}\`, {`,
      '    ...init,',
      `    method: '${operation.method}'`,
      '  });',
      '',
      '  if (!response.ok) {',
      `    throw new Error(\`${operation.operationId} failed with status \${response.status}\`);`,
      '  }',
      '',
      `  return response.json() as Promise<${operation.responseType}>;`,
      '}',
      ''
    );
  }

  return `${lines.join('\n').trimEnd()}\n`;
}
