import { Executor } from '@stratix/core';
import type ExecutorService from '../services/ExecutorService.js';

@Executor({
  name: 'samplePluginExecutor',
  description: 'Sample plugin executor generated by Stratix CLI'
})
export default class SampleExecutor {
  constructor(private readonly executorService: ExecutorService) {}

  async execute(): Promise<{
    success: boolean;
    data: Record<string, unknown>;
  }> {
    return {
      success: true,
      data: await this.executorService.loadPayload()
    };
  }
}
