/**
 * @stratix/database 迁移管理器模块
 */

import fs from 'fs';
import { Knex } from 'knex';
import path from 'path';
import { DatabaseConfig, ModelStatic } from '../types/index.js';
import { MigrationGenerator } from './generator.js';

/**
 * 自定义Knex迁移概要接口
 */
interface MigrationSummary {
  name: string;
  migration_time: string | null;
}

/**
 * 迁移管理器类
 * 负责数据库迁移的执行和自动生成
 */
export class MigrationManager {
  /**
   * Knex实例
   */
  private knex: Knex;

  /**
   * 迁移配置
   */
  private config: DatabaseConfig['migrations'];

  /**
   * 模型类数组
   */
  private models: ModelStatic[] = [];

  /**
   * 默认模板文件路径
   */
  private readonly DEFAULT_TEMPLATE_PATH = path.join(
    __dirname,
    'templates',
    'default.js'
  );

  /**
   * 构造函数
   *
   * @param knex Knex实例
   * @param config 数据库配置
   */
  constructor(knex: Knex, config: DatabaseConfig) {
    this.knex = knex;
    this.config = config.migrations || {};
  }

  /**
   * 设置可用的模型类
   *
   * @param models 模型类数组
   */
  public setModels(models: ModelStatic[]): void {
    this.models = models;
  }

  /**
   * 添加模型类
   *
   * @param model 模型类
   */
  public addModel(model: ModelStatic): void {
    if (!this.models.includes(model)) {
      this.models.push(model);
    }
  }

  /**
   * 执行待处理的迁移
   *
   * @returns 执行的迁移文件名数组
   */
  public async migrate(): Promise<string[]> {
    // 自动生成迁移
    if (this.config?.autoGenerate && this.models.length > 0) {
      await this.generateMigrations();
    }

    // 执行迁移
    const [batchNo, log] = await this.knex.migrate.latest();
    return log;
  }

  /**
   * 回滚最后一批迁移
   *
   * @returns 回滚的迁移文件名数组
   */
  public async rollback(): Promise<string[]> {
    const [batchNo, log] = await this.knex.migrate.rollback();
    return log;
  }

  /**
   * 回滚所有迁移
   *
   * @returns 回滚的迁移文件名数组
   */
  public async reset(): Promise<string[]> {
    const options = { all: true } as unknown as Knex.MigratorConfig;
    const [batchNo, log] = await this.knex.migrate.rollback(options);
    return log;
  }

  /**
   * 查看当前迁移状态
   *
   * @returns 迁移状态信息
   */
  public async status(): Promise<MigrationSummary[]> {
    return this.knex.migrate.status() as unknown as Promise<MigrationSummary[]>;
  }

  /**
   * 自动生成迁移文件
   *
   * @returns 生成的迁移文件路径数组
   */
  public async generateMigrations(): Promise<string[]> {
    if (!this.config) {
      throw new Error('迁移配置未设置');
    }

    const {
      autoGenerateDirectory,
      directory,
      tablePrefix = '',
      templateFile
    } = this.config;

    // 确定迁移目录
    const migrationDir = autoGenerateDirectory || directory;
    if (!migrationDir) {
      throw new Error('未指定迁移目录');
    }

    // 确保目录存在
    if (typeof migrationDir === 'string' && !fs.existsSync(migrationDir)) {
      fs.mkdirSync(migrationDir, { recursive: true });
    }

    // 确定模板文件
    const template = templateFile || this.DEFAULT_TEMPLATE_PATH;

    // 生成迁移
    return MigrationGenerator.generateFromModels(
      this.models,
      migrationDir as string,
      tablePrefix
    );
  }

  /**
   * 从指定模型生成迁移文件
   *
   * @param modelClass 模型类
   * @returns 生成的迁移文件路径
   */
  public async generateMigrationFromModel(
    modelClass: ModelStatic
  ): Promise<string> {
    if (!this.config) {
      throw new Error('迁移配置未设置');
    }

    const {
      autoGenerateDirectory,
      directory,
      tablePrefix = '',
      templateFile
    } = this.config;

    // 确定迁移目录
    const migrationDir = autoGenerateDirectory || directory;
    if (!migrationDir) {
      throw new Error('未指定迁移目录');
    }

    // 确保目录存在
    if (typeof migrationDir === 'string' && !fs.existsSync(migrationDir)) {
      fs.mkdirSync(migrationDir, { recursive: true });
    }

    return MigrationGenerator.generateFromModel({
      modelClass,
      directory: migrationDir as string,
      tablePrefix,
      templateFile
    });
  }
}
