import { TaskStatus, } from '@/types/task.types';
// Mock 运行中任务数据 - 扁平化结构，通过parent_id建立层级关系
export const mockRunningTasks = [
    // 根任务1：课程表同步任务
    {
        id: 'task-001',
        parent_id: null,
        name: '课程表同步任务',
        description: '从教务系统同步最新的课程表数据',
        task_type: 'course_sync',
        status: TaskStatus.RUNNING,
        priority: 5,
        progress: 65,
        executor_name: 'sync-executor-01',
        metadata: {
            sync_range: '2024-2025-1',
            start_time: '2024-01-15T09:00:00Z',
        },
        created_at: '2024-01-15T09:00:00Z',
        updated_at: '2024-01-15T09:30:00Z',
        started_at: '2024-01-15T09:00:00Z',
        completed_at: null,
        children: [],
    },
    // 子任务1-1：同步教师信息
    {
        id: 'task-001-1',
        parent_id: 'task-001',
        name: '同步教师信息',
        description: '同步教师基本信息和工号映射',
        task_type: 'teacher_sync',
        status: TaskStatus.SUCCESS,
        priority: 3,
        progress: 100,
        executor_name: 'sync-executor-01',
        metadata: {
            synced_count: 245,
        },
        created_at: '2024-01-15T09:01:00Z',
        updated_at: '2024-01-15T09:10:00Z',
        started_at: '2024-01-15T09:01:00Z',
        completed_at: '2024-01-15T09:10:00Z',
        children: [],
    },
    // 子任务1-2：同步课程信息
    {
        id: 'task-001-2',
        parent_id: 'task-001',
        name: '同步课程信息',
        description: '同步课程基本信息和开课计划',
        task_type: 'course_info_sync',
        status: TaskStatus.RUNNING,
        priority: 4,
        progress: 75,
        executor_name: 'sync-executor-01',
        metadata: {
            total_courses: 180,
            synced_courses: 135,
        },
        created_at: '2024-01-15T09:10:00Z',
        updated_at: '2024-01-15T09:30:00Z',
        started_at: '2024-01-15T09:10:00Z',
        completed_at: null,
        children: [],
    },
    // 子任务1-3：同步教室信息
    {
        id: 'task-001-3',
        parent_id: 'task-001',
        name: '同步教室信息',
        description: '同步教学楼和教室信息',
        task_type: 'classroom_sync',
        status: TaskStatus.PENDING,
        priority: 2,
        progress: 0,
        executor_name: 'sync-executor-01',
        metadata: {},
        created_at: '2024-01-15T09:00:00Z',
        updated_at: '2024-01-15T09:00:00Z',
        started_at: null,
        completed_at: null,
        children: [],
    },
    // 子子任务1-2-1：验证课程数据
    {
        id: 'task-001-2-1',
        parent_id: 'task-001-2',
        name: '验证课程数据',
        description: '验证已同步课程数据的完整性',
        task_type: 'data_validation',
        status: TaskStatus.RUNNING,
        priority: 3,
        progress: 40,
        executor_name: 'validation-worker',
        metadata: {
            validation_rules: [
                'schedule_conflict',
                'teacher_availability',
                'room_capacity',
            ],
        },
        created_at: '2024-01-15T09:20:00Z',
        updated_at: '2024-01-15T09:35:00Z',
        started_at: '2024-01-15T09:20:00Z',
        completed_at: null,
        children: [],
    },
    // 根任务2：考勤数据清理
    {
        id: 'task-002',
        parent_id: null,
        name: '考勤数据清理',
        description: '清理过期的考勤记录数据',
        task_type: 'attendance_cleanup',
        status: TaskStatus.PENDING,
        priority: 2,
        progress: 0,
        executor_name: 'cleanup-executor',
        metadata: {
            cleanup_before: '2023-12-31',
        },
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
        started_at: null,
        completed_at: null,
        children: [],
    },
    // 子任务2-1：备份旧数据
    {
        id: 'task-002-1',
        parent_id: 'task-002',
        name: '备份旧数据',
        description: '在清理前备份要删除的数据',
        task_type: 'data_backup',
        status: TaskStatus.PENDING,
        priority: 1,
        progress: 0,
        executor_name: 'backup-worker',
        metadata: {},
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
        started_at: null,
        completed_at: null,
        children: [],
    },
    // 子任务2-2：执行清理
    {
        id: 'task-002-2',
        parent_id: 'task-002',
        name: '执行清理',
        description: '删除过期的考勤记录',
        task_type: 'data_cleanup',
        status: TaskStatus.PENDING,
        priority: 2,
        progress: 0,
        executor_name: 'cleanup-worker',
        metadata: {},
        created_at: '2024-01-15T10:00:00Z',
        updated_at: '2024-01-15T10:00:00Z',
        started_at: null,
        completed_at: null,
        children: [],
    },
    // 根任务3：日程同步到WPS
    {
        id: 'task-003',
        parent_id: null,
        name: '日程同步到WPS',
        description: '将课程表同步到WPS协作日程',
        task_type: 'wps_calendar_sync',
        status: TaskStatus.PAUSED,
        priority: 7,
        progress: 35,
        executor_name: 'wps-sync-executor',
        metadata: {
            calendar_id: 'cal-123456',
            sync_mode: 'incremental',
        },
        created_at: '2024-01-15T08:30:00Z',
        updated_at: '2024-01-15T09:15:00Z',
        started_at: '2024-01-15T08:30:00Z',
        completed_at: null,
        children: [],
    },
    // 子任务3-1：创建日程事件
    {
        id: 'task-003-1',
        parent_id: 'task-003',
        name: '创建日程事件',
        description: '为每个课程创建WPS日程事件',
        task_type: 'calendar_event_creation',
        status: TaskStatus.PAUSED,
        priority: 6,
        progress: 35,
        executor_name: 'calendar-worker',
        metadata: {
            total_events: 120,
            created_events: 42,
        },
        created_at: '2024-01-15T08:35:00Z',
        updated_at: '2024-01-15T09:15:00Z',
        started_at: '2024-01-15T08:35:00Z',
        completed_at: null,
        children: [],
    },
];
// Mock 已完成任务数据
export const mockCompletedTasks = [
    {
        id: 'task-100',
        parent_id: null,
        name: '用户数据同步',
        description: '从LDAP同步用户信息',
        task_type: 'user_sync',
        status: TaskStatus.SUCCESS,
        priority: 6,
        progress: 100,
        executor_name: 'user-sync-executor',
        metadata: {
            synced_users: 1250,
            sync_type: 'full',
        },
        created_at: '2024-01-14T10:00:00Z',
        updated_at: '2024-01-14T10:30:00Z',
        started_at: '2024-01-14T10:00:00Z',
        completed_at: '2024-01-14T10:30:00Z',
    },
    {
        id: 'task-101',
        parent_id: null,
        name: '数据库备份',
        description: '定期备份系统数据库',
        task_type: 'database_backup',
        status: TaskStatus.SUCCESS,
        priority: 9,
        progress: 100,
        executor_name: 'backup-executor',
        metadata: {
            backup_size: '2.5GB',
            backup_location: '/backups/2024-01-14',
        },
        created_at: '2024-01-14T02:00:00Z',
        updated_at: '2024-01-14T02:45:00Z',
        started_at: '2024-01-14T02:00:00Z',
        completed_at: '2024-01-14T02:45:00Z',
    },
    {
        id: 'task-102',
        parent_id: null,
        name: '系统监控检查',
        description: '检查系统各项指标状态',
        task_type: 'health_check',
        status: TaskStatus.FAILED,
        priority: 4,
        progress: 100,
        executor_name: 'monitor-executor',
        metadata: {
            error: 'Database connection timeout',
            check_items: ['database', 'cache', 'queue'],
        },
        created_at: '2024-01-14T06:00:00Z',
        updated_at: '2024-01-14T06:05:00Z',
        started_at: '2024-01-14T06:00:00Z',
        completed_at: '2024-01-14T06:05:00Z',
    },
];
// Mock 任务统计数据
export const mockTaskStats = {
    total: 25,
    pending: 3,
    running: 2,
    paused: 1,
    success: 15,
    failed: 4,
    cancelled: 0,
    timeout: 0,
    last_updated: '2024-01-15T10:30:00Z',
};
// Mock 分页响应
export const mockTasksResponse = {
    items: mockRunningTasks,
    total: mockRunningTasks.length,
    page: 1,
    page_size: 20,
    total_pages: 1,
    has_next: false,
    has_prev: false,
};
export const mockCompletedTasksResponse = {
    items: mockCompletedTasks,
    total: mockCompletedTasks.length,
    page: 1,
    page_size: 20,
    total_pages: 1,
    has_next: false,
    has_prev: false,
};
//# sourceMappingURL=mock-data.js.map