--
-- Table structure for table `icalink_attendance_records_history`
--
CREATE TABLE `icalink_attendance_records` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `attendance_course_id` bigint(20) NOT NULL COMMENT '关联课程ID',
  `student_id` varchar(100) NOT NULL COMMENT '学生ID',
  `student_name` varchar(200) NOT NULL COMMENT '学生姓名',
  `class_name` varchar(200) DEFAULT NULL COMMENT '班级名称',
  `major_name` varchar(200) DEFAULT NULL COMMENT '专业名称',
  `status` enum('not_started','present','absent','leave','pending_approval','leave_pending','late','truant') NOT NULL DEFAULT 'not_started' COMMENT '签到状态 (v7 新增 truant)',
  `checkin_time` datetime DEFAULT NULL COMMENT '签到时间',
  `checkin_location` varchar(500) DEFAULT NULL COMMENT '签到位置描述',
  `checkin_latitude` decimal(10,7) DEFAULT NULL COMMENT '签到纬度',
  `checkin_longitude` decimal(10,7) DEFAULT NULL COMMENT '签到经度',
  `checkin_accuracy` int(11) DEFAULT NULL COMMENT '位置精度(米)',
  `ip_address` varchar(45) DEFAULT NULL COMMENT '签到IP地址',
  `user_agent` varchar(1000) DEFAULT NULL COMMENT '用户代理信息',
  `is_late` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否迟到',
  `late_minutes` int(11) DEFAULT NULL COMMENT '迟到分钟数',
  `remark` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(100) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '更新人',
  `metadata` json DEFAULT NULL COMMENT '扩展元数据',
  `last_checkin_source` enum('regular','window','manual') DEFAULT NULL COMMENT '最后签到来源',
  `last_checkin_reason` varchar(255) DEFAULT NULL COMMENT '最后签到原因说明',
  `manual_override_by` varchar(100) DEFAULT NULL COMMENT '手动补卡人（教师ID）',
  `manual_override_time` datetime DEFAULT NULL COMMENT '手动补卡时间',
  `manual_override_reason` varchar(500) DEFAULT NULL COMMENT '手动补卡原因说明',
  `auto_marked_at` datetime DEFAULT NULL COMMENT '系统自动标记时间',
  `window_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联的验证签到窗口ID',
  PRIMARY KEY (`id`),
  KEY `idx_course_student_hist` (`attendance_course_id`,`student_id`),
  KEY `idx_student_id_hist` (`student_id`),
  KEY `idx_status_hist` (`status`),
  KEY `idx_checkin_time_hist` (`checkin_time`),
  KEY `idx_created_at_hist` (`created_at`),
  KEY `idx_window_id_hist` (`window_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学生签到记录历史归档表';