CREATE TABLE `icasync_attendance_courses` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `juhe_renwu_id` int(11) NOT NULL COMMENT '关联聚合任务ID',
  `external_id` varchar(200) NOT NULL COMMENT '关联外部ID',
  `course_code` varchar(60) NOT NULL COMMENT '课程代码',
  `course_name` varchar(500) NOT NULL COMMENT '课程名称',
  `semester` varchar(20) NOT NULL COMMENT '学年学期',
  `teaching_week` int(11) NOT NULL COMMENT '教学周(来自juhe_renwu.jxz)',
  `week_day` int(11) NOT NULL COMMENT '周次-星期几(来自juhe_renwu.zc)',
  `teacher_codes` varchar(500) COMMENT '教师工号列表(逗号分隔)',
  `teacher_names` varchar(500) COMMENT '教师姓名列表',
  `class_location` varchar(1000) COMMENT '上课地址(教学楼+教室)',
  `start_time` datetime NOT NULL COMMENT '开始时间(RFC3339格式)',
  `end_time` datetime NOT NULL COMMENT '结束时间(RFC3339格式)',
  `periods` varchar(256) COMMENT '节次',
  `time_period` varchar(2) NOT NULL COMMENT '时间段(am/pm)',
  `attendance_enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用签到',
  `attendance_start_offset` int(11) DEFAULT -10 COMMENT '签到开始时间偏移(分钟)',
  `attendance_end_offset` int(11) DEFAULT 10 COMMENT '签到结束时间偏移(分钟)',
  `late_threshold` int(11) DEFAULT 10 COMMENT '迟到阈值(分钟)',
  `auto_absent_after` int(11) DEFAULT 60 COMMENT '自动标记缺勤时间(分钟)',
  `need_checkin` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否需要签到',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(50) COMMENT '创建人',
  `updated_by` varchar(50) COMMENT '更新人',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT '软删除时间',
  `deleted_by` varchar(50) DEFAULT NULL COMMENT '删除者',
  `metadata` json DEFAULT NULL COMMENT '元数据',
  PRIMARY KEY (`id`),
  KEY `idx_course_code_semester` (`course_code`, `semester`),
  KEY `idx_semester_enabled` (`semester`, `attendance_enabled`),
  KEY `idx_teaching_week` (`teaching_week`),
  KEY `idx_week_day` (`week_day`),
  KEY `idx_teacher_codes` (`teacher_codes`(255)),
  KEY `idx_deleted_at` (`deleted_at`),
  KEY `idx_semester_deleted` (`semester`, `deleted_at`),
  KEY `idx_course_semester_deleted` (`course_code`, `semester`, `deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='签到课程表-存储需要签到的课程信息';