{
  "name": "{{packageName}}",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build && tsc -b",
    "lint": "eslint .",
    "preview": "vite preview",
    "test": "vitest run --config vitest.config.ts",
    "test:coverage": "vitest run --config vitest.config.ts --coverage",
    "typecheck": "tsc -b"
  },
  "dependencies": {
    "@assistant-ui/react": "^0.14.21",
    "@assistant-ui/react-markdown": "^0.14.3",
    "@hookform/resolvers": "^5.4.0",
    "@radix-ui/react-avatar": "^1.1.12",
    "@radix-ui/react-dialog": "^1.1.16",
    "@radix-ui/react-dropdown-menu": "^2.1.17",
    "@radix-ui/react-separator": "^1.1.9",
    "@radix-ui/react-slot": "^1.2.5",
    "@radix-ui/react-tooltip": "^1.2.9",
    "@tanstack/react-query": "^5.101.0",
    "@tanstack/react-query-devtools": "^5.101.0",
    "@tanstack/react-router": "^1.170.15",
    "@tanstack/react-router-devtools": "^1.167.0",
    "@tanstack/react-table": "^8.21.3",
    "@tanstack/react-virtual": "^3.14.2",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "cmdk": "^1.1.1",
    "lucide-react": "^1.18.0",
    "next-themes": "^0.4.6",
    "radix-ui": "^1.5.0",
    "react": "^19.2.7",
    "react-dom": "^19.2.7",
    "react-hook-form": "^7.79.0",
    "remark-gfm": "^4.0.1",
    "sonner": "^2.0.7",
    "tailwind-merge": "^3.6.0",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^4.4.3",
    "zustand": "^5.0.14"
  },
  "devDependencies": {
    "@tailwindcss/vite": "^4.3.1",
    "@tanstack/router-plugin": "^1.168.18",
    "@types/node": "^25.9.3",
    "@types/react": "^19.2.17",
    "@types/react-dom": "^19.2.3",
    "@typescript-eslint/eslint-plugin": "^8.61.0",
    "@typescript-eslint/parser": "^8.61.0",
    "@vitejs/plugin-react-swc": "^4.3.1",
    "@vitest/coverage-v8": "^4.1.8",
    "autoprefixer": "^10.5.0",
    "eslint": "^10.5.0",
    "eslint-import-resolver-typescript": "^4.4.5",
    "eslint-plugin-import": "^2.32.0",
    "eslint-plugin-prettier": "^5.5.6",
    "postcss": "^8.5.15",
    "prettier": "^3.8.4",
    "tailwindcss": "^4.3.1",
    "typescript": "^6.0.3",
    "vite": "^8.0.16",
    "vitest": "^4.1.8"
  },
  "engines": {
    "node": ">=24.0.0"
  }
}
